parameters:

services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  Jgmullor\ExampleApp\Command\ExampleCommand:
    class: Jgmullor\ExampleApp\Command\ExampleCommand
    autoconfigure: true